language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

python: 3.5

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g gulp
  - cd archive_builder
  - python build_archive.py
  - cd ..

script:
  - gulp dist

after_script:
  - cd dist
  - git init
  - git config user.name "cutelittleturtle"
  - git config user.email "31291893+cutelittleturtle@users.noreply.github.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  
 
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/cutelittleturtle/suisuiarchive.git
